import { z } from 'zod';

export const CrearConfiguracionSchema = z.object({
    logo: z.string().trim().max(500).optional(),
    moneda: z.string().trim().min(1).max(10).default('USD'),
    simboloMoneda: z.string().trim().min(1).max(5).default('$'),
    iva: z.number().finite().min(0).max(100).default(15),
    zonaHoraria: z.string().trim().min(1).max(100).default('America/Guayaquil'),
    formatoFecha: z.string().trim().min(1).max(30).default('dd/MM/yyyy'),
    idioma: z.string().trim().min(2).max(10).default('es'),
    prefijoCompra: z.string().trim().min(1).max(20).default('COM'),
    prefijoVenta: z.string().trim().min(1).max(20).default('VEN'),
    prefijoCotizacion: z.string().trim().min(1).max(20).default('COT'),
    prefijoFactura: z.string().trim().min(1).max(20).default('FAC'),
    prefijoGasto: z.string().trim().min(1).max(20).default('GAS'),
    prefijoTransferencia: z.string().trim().min(1).max(20).default('TRF'),
    prefijoDevolucion: z.string().trim().min(1).max(20).default('DEV'),
    permitirStockNegativo: z.boolean().default(false),
    controlarLotes: z.boolean().default(false),
    controlarSeries: z.boolean().default(false),
    actualizarCostoPromedio: z.boolean().default(true),
    aprobarCompras: z.boolean().default(false),
    aprobarVentas: z.boolean().default(false),
    permitirDescuento: z.boolean().default(true),
    porcentajeMaxDescuento: z.number().finite().min(0).max(100).default(20),
    dobleFactor: z.boolean().default(false),
    expiracionPassword: z.number().int().min(1).max(3650).default(90),
    longitudMinimaPassword: z.number().int().min(4).max(128).default(8),
    intentosLogin: z.number().int().min(1).max(100).default(5),
    bloqueoMinutos: z.number().int().min(1).max(1440).default(30),
    auditoriaActiva: z.boolean().default(true),
    diasRetencionAuditoria: z.number().int().min(1).max(3650).default(365),
    enviarCorreo: z.boolean().default(true),
    enviarNotificaciones: z.boolean().default(true),
    mantenimiento: z.boolean().default(false)
}).strict();

export const ActualizarConfiguracionSchema = z.object({
    logo: z.string().trim().max(500).nullable().optional(),
    moneda: z.string().trim().min(1).max(10).optional(),
    simboloMoneda: z.string().trim().min(1).max(5).optional(),
    iva: z.number().finite().min(0).max(100).optional(),
    zonaHoraria: z.string().trim().min(1).max(100).optional(),
    formatoFecha: z.string().trim().min(1).max(30).optional(),
    idioma: z.string().trim().min(2).max(10).optional(),
    prefijoCompra: z.string().trim().min(1).max(20).optional(),
    prefijoVenta: z.string().trim().min(1).max(20).optional(),
    prefijoCotizacion: z.string().trim().min(1).max(20).optional(),
    prefijoFactura: z.string().trim().min(1).max(20).optional(),
    prefijoGasto: z.string().trim().min(1).max(20).optional(),
    prefijoTransferencia: z.string().trim().min(1).max(20).optional(),
    prefijoDevolucion: z.string().trim().min(1).max(20).optional(),
    permitirStockNegativo: z.boolean().optional(),
    controlarLotes: z.boolean().optional(),
    controlarSeries: z.boolean().optional(),
    actualizarCostoPromedio: z.boolean().optional(),
    aprobarCompras: z.boolean().optional(),
    aprobarVentas: z.boolean().optional(),
    permitirDescuento: z.boolean().optional(),
    porcentajeMaxDescuento: z.number().finite().min(0).max(100).optional(),
    dobleFactor: z.boolean().optional(),
    expiracionPassword: z.number().int().min(1).max(3650).optional(),
    longitudMinimaPassword: z.number().int().min(4).max(128).optional(),
    intentosLogin: z.number().int().min(1).max(100).optional(),
    bloqueoMinutos: z.number().int().min(1).max(1440).optional(),
    auditoriaActiva: z.boolean().optional(),
    diasRetencionAuditoria: z.number().int().min(1).max(3650).optional(),
    enviarCorreo: z.boolean().optional(),
    enviarNotificaciones: z.boolean().optional(),
    mantenimiento: z.boolean().optional()
}).strict();

export type CrearConfiguracionDto = z.infer<typeof CrearConfiguracionSchema>;
export type ActualizarConfiguracionDto = z.infer<typeof ActualizarConfiguracionSchema>;