-- AlterTable
ALTER TABLE "public"."Configuracion" ADD COLUMN     "actualizarCostoPromedio" BOOLEAN NOT NULL DEFAULT true,
ADD COLUMN     "aprobarCompras" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "aprobarVentas" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "auditoriaActiva" BOOLEAN NOT NULL DEFAULT true,
ADD COLUMN     "bloqueoMinutos" INTEGER NOT NULL DEFAULT 30,
ADD COLUMN     "controlarLotes" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "controlarSeries" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "diasRetencionAuditoria" INTEGER NOT NULL DEFAULT 365,
ADD COLUMN     "dobleFactor" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "enviarCorreo" BOOLEAN NOT NULL DEFAULT true,
ADD COLUMN     "enviarNotificaciones" BOOLEAN NOT NULL DEFAULT true,
ADD COLUMN     "expiracionPassword" INTEGER NOT NULL DEFAULT 90,
ADD COLUMN     "idioma" TEXT NOT NULL DEFAULT 'es',
ADD COLUMN     "intentosLogin" INTEGER NOT NULL DEFAULT 5,
ADD COLUMN     "longitudMinimaPassword" INTEGER NOT NULL DEFAULT 8,
ADD COLUMN     "mantenimiento" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "permitirDescuento" BOOLEAN NOT NULL DEFAULT true,
ADD COLUMN     "permitirStockNegativo" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "porcentajeMaxDescuento" DECIMAL(5,2) NOT NULL DEFAULT 20,
ADD COLUMN     "prefijoFactura" TEXT NOT NULL DEFAULT 'FAC';
